config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}
  devise_scope :user do
    get 'users/list' => 'users#index'
    get 'users/report' => 'users#report'
    get 'users/:id' => 'users#show'
    delete '/users/logout' => 'devise/sessions#destroy'
  end
  get 'users/edit'
  post 'users/edit_save'
  resources :users
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  root 'home#page'
  get 'home/page'
  get 'home/support_contact'
  get 'home/about'

  get 'seed/start'
  post 'seed/start'
  get 'seed/load_file'
  post 'seed/save_file'
  post 'seed/discovery'
  get 'seed/distest'

  get 'domains/index'
  get 'domains/show'
  get 'domains/edit'
  post 'domains/edit_domain'
  post 'domains/save_domain'
  post 'domains/edit'
  post 'domains/update'
  delete 'domains/destroy'
  get 'domains/load_file'
  post 'domains/save_file'
  get 'domains/import'
  get 'domains/search'
  get 'domains/search_list'
  post 'domains/search_list'
  post 'domains/save_import'

  get 'cidrs/index'
  get 'cidrs/edit'
  get 'cidrs/import'
  post 'cidrs/save_import'
  post 'cidrs/edit'
  get 'cidrs/load_file'
  post 'cidrs/save_file'

  get 'hosts/index'
  post 'hosts/edit'
  get 'hosts/load_file'
  post 'hosts/save_file'

  get 'support/faq'
  get 'support/contact'

  get 'sites/index'
  get 'sites/show'
  post 'sites/edit'
  get 'sites/load_file'
  post 'sites/save_file'
  post 'sites/search'
  post 'sites/download'

  get 'logs/list'
  get 'logs/show'
  post 'logs/download'

  get 'yml_settings/index'
  get 'yml_settings/load_file'
  post 'yml_settings/save_file'

  get 'reports/index'
  get 'reports/new'
  get 'reports/download'
  get 'reports/download_all'
  resources :reports

  resources :uploads, only: [:new, :create, :destroy]
  get '/uploads/dt'
  get '/uploads/division_1'
  get '/uploads/division_2'
  get '/uploads/division_3'
  post "uploads/update"
  get "uploads/refresh"
  get "uploads/create"
  get "uploads/alert_uploads"

  get 'domain_map/show'
  post 'domain_map/show'

end

app/models/user.rb
#--
# www_wmap
#
# A  Ruby application for enterprise web application asset tracking
#
# Developed by Sam (Yang) Li, <yang.li@owasp.org>.
#
#++

class User < ApplicationRecord

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :ldap_authenticatable, :database_authenticatable, # :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :timeoutable, :authentication_keys => [:username]
         attr_accessor :login
         # for client side validations
         validates :username, :password, presence: true
         validates_format_of :username, :with => /\A[a-z]+[0-9]*\z/i, :allow_blank => true, :message => "Your  Domain ID should contain letters and numbers only."
         validates_length_of :password, :minimum => 8, :allow_blank => true

         # refer to the smaple at: https://github.com/RailsApps/rails-devise-roles
         enum role: {user: 100, bronze: 50, silver: 40, gold: 30, platinum: 20, admin: 0 }
         after_initialize :set_default_role, :if => :new_record?

         def set_default_role
           self.role ||= :user
         end

         def self.find_first_by_auth_conditions(warden_conditions)
           conditions = warden_conditions.dup
           if login = conditions.delete(:login)
             where(conditions).where(["lower(username) = :value ", { :value => login.downcase }]).first
           else
             if conditions[:username].nil?
               where(conditions).first
             else
               where(username: conditions[:username]).first
             end
           end
         end

         def ldap_before_save
           #
           self.department = Devise::LDAP::Adapter.get_ldap_param(self.username,"department").first
           self.name = Devise::LDAP::Adapter.get_ldap_param(self.username,"name").first
           self.email = Devise::LDAP::Adapter.get_ldap_param(self.username,"mail").first
           self.employee_number = Devise::LDAP::Adapter.get_ldap_param(self.username,"employeeNumber").first
           self.employee_type = Devise::LDAP::Adapter.get_ldap_param(self.username,"employeeType").first
           self.dn = Devise::LDAP::Adapter.get_dn(self.username)
=begin
           # Assign user role based on user department
           case  dptm
           when "Human Resources"
             self.role = :hr
           when "Finance"
             self.role = :fa
           else
             self.role = :user
           end
           Rails.logger.debug ("Assign user role to #{self.username}: #{self.role}")
=end
         end
         scope :department, -> (department) { where department: department}

end

app/controllers/users_controller.rb
#--
# www_wmap
#
# A  Ruby application for enterprise web application asset tracking
#
# Developed by Sam (Yang) Li, <yang.li@owasp.org>.
#
#++

class UsersController < ApplicationController

  before_action :authenticate_user!
  before_action :admin_only
  #helper_method :sort_column, :sort_direction

  def edit
    @user = User.find(params[:id])
    respond_to do |format|
        format.js
    end
  end

  def edit_save
    @user = User.find(params[:id])
    # add the following line to bypass password validations in Rails 4.2
    @user.password = "!@#$%^&*----"
    @user.name = params[:name]
    @user.email = params[:email]
    @user.department = params[:department]
    if @user.save!
      redirect_to users_path, :alert => "User save successfully."
    else
      flash.now[:error] = "User save error. "
    end
  end

  def index
    @users = User.order(sort_column + " " + sort_direction)
    dept=Hash.new; @users.map {|a| dept[a.department]=true unless dept.key?(a.department) }
    @department_list=Array.new; dept.each {|key,val| @department_list.push(key) unless key.nil? }
    @department_list.sort!
    filtering_params(params).each do |key, value|
      next if value.nil?
      @users = @users.public_send(key, value) if value.present?
    end
  end

  def show
    @user = User.find(params[:id])
    unless current_user.admin?
      unless @user == current_user
        redirect_back :fallback_location => root_path, :alert => "Access denied."
      end
    end
  end

  def update
    @user = User.find(params[:id])
    # add the following line to bypass password validations in Rails 4.2
    @user.password = "!@#$%^&*----"
    #render plain: secure_params.inspect
#=begin
    if @user.update!(secure_params)
      redirect_to users_path, :notice => "User updated successfully."
    else
      redirect_to users_path, :alert => "Unable to update user."
    end
#=end
  end

  def report
    # Respond to the Download request
      index
      wb = RubyXL::Workbook.new
      download = wb.worksheets[0]
      download.sheet_name = 'User Report'
      # set the header row
      download.add_cell(0,0, "Name")
      download.add_cell(0,1, "Email")
      download.add_cell(0,2, "Department")
      download.add_cell(0,3, "Role")
      # fill the rest of the rows
      my_row=0
      @users.each do |aa|
          my_row += 1
          next if aa.nil?
          download.add_cell(my_row,0, aa['username'].titleize)
          download.add_cell(my_row,1, aa['email'])
          download.add_cell(my_row,2, aa['department'])
          download.add_cell(my_row,3, aa['role'])
      end
      send_data wb.stream.string, filename: "Wmap_User.xlsx", disposition: 'attachment'
      wb = nil

  end

  def destroy
    user = User.find(params[:id])
    user.destroy
    redirect_to users_path, :notice => "User deleted."
  end

private

  def filtering_params(params)
    params.slice(:department)
  end

  def secure_params
    params.require(:user).permit(:role,:email,:username)
    #['role', 'admin']
  end

  def sort_column
    User.column_names.include?(params[:sort]) ? params[:sort] : "username"
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end

end

app/helpers/users_helper.rb
#--
# www_wmap
#
# A  Ruby application for enterprise web application asset tracking
#
# Developed by Sam (Yang) Li, <yang.li@owasp.org>.
#
#++

module UsersHelper
  def sortable(column, title = nil)
    title ||= column.titleize
    css_class = if column != sort_column
                    nil
                elsif sort_direction == 'asc'
                    'glyphicon glyphicon-chevron-up'
                else
                    'glyphicon glyphicon-chevron-down'
                end
    direction = column == sort_column && sort_direction == 'asc' ? 'desc' : 'asc'
    link_to "#{title} <span class='#{css_class}'></span>".html_safe, sort: column, direction: direction
  end


end

app/views/users/_edit_user.html.erb
<!-- Implementation based on this technie: https://github.com/colorfulfool/rails-popup -->
<% remote = request.xhr? %>
<h4>&nbsp;&nbsp;Update User Information
</h4>

<%= form_tag(controller: "users", action: "edit_save", remote: remote, method: "post") do  %>
  <table class="table table-striped" style="border: 1">
      <tr>
          <td>ID:
          </td>
          <td><%= @user.username %>
          </td>
          <td><%= text_field_tag :username, nil, class: 'form-control', value: @user.username%></td>
      </tr>
      <tr>
          <td>Name:
          </td>
          <td><%= @user.name %>
          </td>
          <td><%= text_field_tag :name, nil, class: 'form-control', value: @user.name%></td>
      </tr>
      <tr>
          <td>Department:
          </td>
          <td><%= @user.department %>
          </td>
          <td><%= text_field_tag :department, nil, class: 'form-control', value: @user.department%></td>
      </tr>
      <tr>
          <td>Email:
          </td>
          <td><%= @user.email %>
          </td>
          <td><%= text_field_tag :email, nil, class: 'form-control', value: @user.email%></td>
      </tr>
      <%= hidden_field_tag :id, @user.id %>
  </table>
  <p>&nbsp;&nbsp;<button class="btn btn-default btn-sm" type="submit" data-disable-with="Please wait...">Submit</button>
      &nbsp;&nbsp;<input type="button" onclick="window.parent.location = window.parent.location.href;" value="Back" class="btn btn-default btn-sm">
  </p>
<% end %>

app/views/users/_sub_menu.html.erb
  <div class="col-md-3 col-lg-3">
    <button class="btn btn-default dropdown-toggle" data-toggle="dropdown">
      User Manager
      <span class="caret"></span>
    </button>
    <ul class="dropdown-menu">
      <li><a href="/users/list">User List</a></li>
      <li><a href="/users/report">Download User Report</a></li>
    </ul>
  </div>

app/views/users/_user.html.erb
<td>
  <%= link_to user.username, user %>
</td>
<td>
  <a href='mailto:<%= user.email %>'><%= user.email %></a>
</td>
<td>
  <%= link_to user.name, user if user.name %>
</td>
<td>
  <%= user.department %>
</td>
<td>
  <%= form_for user do |f| %>
    <%= f.select(:role, User.roles.keys.map {|role| [role.titleize,role]}) %>
    <%= f.submit 'Update', :id => 'submit_1', :class => 'btn btn-default btn-sm' %>
  <% end %>
</td>
<td>
  <%= link_to("Delete user", user_path(user), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'btn btn-default btn-sm') unless user == current_user %>
</td>

app/views/users/edit.js.erb
User = Popup("<%=j render :partial => 'users/edit_user', :format => :html %>", {width: 800}).show('up')

app/views/users/index.html.erb
<div class="row">
</div>
<p><p>
<div class="container">
  <div class="row">
    <%= render 'sub_menu' %>
    <div class="pull-right col-md-6 col-lg-6">
      <form class="form-inline form-group">
        <%= hidden_field_tag :direction, params[:direction] %>
        <%= hidden_field_tag :sort, params[:sort] %>
        <%= select("department", "", @department_list, {}, {class: "form-control", id: "slt_2"}) %>
          <button id="btn_1" class="btn btn-default" type="submit">Filter</button>
          <span class="glyphicon glyphicon-filter"></span>
          <% if params[:department].present? %>
            <a href="/users"><span class="glyphicon glyphicon-remove"></span></a>
          <% end %>
      </form>
    </div>
  </div>
  <br />
    <div class="table-responsive">
      <table class="table">
        <tbody>
          <th><%= sortable "username", "ID" %></th>
          <th><%= sortable "email", "Email" %></th>
          <th>Name</th>
          <th>Department</th>
          <th>Role Management</th>
          <th>Remove</th>
          <% @users.each do |user| %>
            <tr>
              <%= render user %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<h3>Web Mapper User</h3>
<br>

<div class="container">
  <div class="row">
    <div class="column">
      <table class="table">
        <tbody>
          <tr><td>ID:</td><td> <%= @user.username if @user.username %></td></tr>
          <tr><td>Name:</td><td> <%= @user.name if @user.name %></td></tr>
          <tr><td>Email:</td><td> <%= @user.email if @user.email %></td></tr>
          <tr><td>Department:</td><td> <%= @user.department if @user.department %></td></tr>
          <tr><td>Created:</td><td> <%= @user.created_at if @user.created_at %></td></tr>
          <tr><td>Last Sign In:</td><td> <%= @user.last_sign_in_at if @user.last_sign_in_at %></td></tr>
          <tr><td>Sign In Count:</td><td> <%= @user.sign_in_count if @user.sign_in_count %></td></tr>

        </tbody>
      </table>
    </div>
    <%= link_to('Update',edit_user_path(:format => :js, :id => @user.id), :remote => true) %>
  </div>
</div>

app/views/users/update.js.erb
//  showing notice only
// <%=j flash[:notice] = 'User role is  changed.' %>