config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}
  devise_scope :user do
    get 'users/list' => 'users#index'
    get 'users/report' => 'users#report'
    get 'users/:id' => 'users#show'
    delete '/users/logout' => 'devise/sessions#destroy'
  end
  get 'users/edit'
  post 'users/edit_save'
  resources :users
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  root 'home#page'
  get 'home/page'
  get 'home/support_contact'
  get 'home/about'

  get 'seed/start'
  post 'seed/start'
  get 'seed/load_file'
  post 'seed/save_file'
  post 'seed/discovery'
  get 'seed/distest'

  get 'domains/index'
  get 'domains/show'
  get 'domains/edit'
  post 'domains/edit_domain'
  post 'domains/save_domain'
  post 'domains/edit'
  post 'domains/update'
  delete 'domains/destroy'
  get 'domains/load_file'
  post 'domains/save_file'
  get 'domains/import'
  get 'domains/search'
  get 'domains/search_list'
  post 'domains/search_list'
  post 'domains/save_import'

  get 'cidrs/index'
  get 'cidrs/edit'
  get 'cidrs/import'
  post 'cidrs/save_import'
  post 'cidrs/edit'
  get 'cidrs/load_file'
  post 'cidrs/save_file'

  get 'hosts/index'
  post 'hosts/edit'
  get 'hosts/load_file'
  post 'hosts/save_file'

  get 'support/faq'
  get 'support/contact'

  get 'sites/index'
  get 'sites/show'
  post 'sites/edit'
  get 'sites/load_file'
  post 'sites/save_file'
  post 'sites/search'
  post 'sites/download'

  get 'logs/list'
  get 'logs/show'
  post 'logs/download'

  get 'yml_settings/index'
  get 'yml_settings/load_file'
  post 'yml_settings/save_file'

  get 'reports/index'
  get 'reports/new'
  get 'reports/download'
  get 'reports/download_all'
  resources :reports

  resources :uploads, only: [:new, :create, :destroy]
  get '/uploads/dt'
  get '/uploads/division_1'
  get '/uploads/division_2'
  get '/uploads/division_3'
  post "uploads/update"
  get "uploads/refresh"
  get "uploads/create"
  get "uploads/alert_uploads"

  get 'domain_map/show'
  post 'domain_map/show'

end

app/models/seed.rb
#--
# www_wmap
#
# A  Ruby application for enterprise web application asset tracking
#
# Developed by Sam (Yang) Li, <yang.li@owasp.org>.
#
#++

class Seed < ApplicationRecord
end

app/controllers/seed_controller.rb
#--
# www_wmap
#
# A  Ruby application for enterprise web application asset tracking
#
# Developed by Sam (Yang) Li, <yang.li@owasp.org>.
#
#++

class SeedController < ApplicationController
  before_action :authenticate_user!

  def start
    #@dir = Pathname.new(Gem.loaded_specs['wmap'].full_gem_path).join('data')
    @dir = Rails.root.join('shared','data')
    Dir.mkdir(@dir, 0750) unless Dir.exist?(@dir)
    @file = @dir.join('seed')
    File.new(@file, 'w+') unless File.exist?(@file)
    @uid = current_user.id
  end

  def show
    #@dir = Pathname.new(Gem.loaded_specs['wmap'].full_gem_path).join('data')
    @dir = Rails.root.join('shared','data')
    Dir.mkdir(@dir, 0750) unless Dir.exist?(@dir)
    @file = @dir.join('seed')
    File.new(@file, 'w+') unless File.exist?(@file)
    @uid = current_user.id
  end

  def load_file
    data = ''
    #@file = Pathname.new(Gem.loaded_specs['wmap'].full_gem_path).join('data', 'seed')
    @file = Rails.root.join('shared','data','seed')
    file = File.open(@file, 'r')
    file.each_line { |line| data += line }
    file.close
    render plain: data
  end

  def save_file
    if platinum_user_and_above?
      #@file = Pathname.new(Gem.loaded_specs['wmap'].full_gem_path).join('data', 'seed')
      @file = Rails.root.join('shared','data','seed')
      file = File.open(@file, 'r')
      @restore = ''
      file.each_line { |line| @restore += line }
      file.close
      file = File.open(@file, 'w+')
      file.write(params[:file_content])
      file.close
      YAML.load_file(@file)
      render json: { message: 'Saving successed.' }
    else
      render json: { message: 'Access denied.' }
    end
  rescue Psych::SyntaxError
    file = File.open(@file, 'w+')
    file.write(@restore)
    file.close
    render json: { message: 'Saving failed, please check your file again.' }
  end

  def discovery
    #UserMailer.discovery_completion_notice("yli8@yahoo.com", "yesterday", "today").deliver_later
    @user= User.find(current_user.id)
    if platinum_user_and_above?
      flash[:notice] = "Discovery is kicked-off in the background ... "
      logger.info "starting the sidekiq worker for the discovery job"
      uid = current_user.id
      DiscoveryWorker.perform_async(uid)
    else
      redirect_back :fallback_location => root_path, :alert => "Access denied."
    end
  end

  def distest
    @user= User.find(current_user.id)
    puts "You're hitting distest controller"
  end



end

app/views/seed/discovery.html.erb
<div class="row">
  <h3>Discovery In Progress!</h3>
</div>

<table class="table">
  <tr>
    <td>
      The discovery is kick-off as a background process. Once it's done you'll receive a confirmation email at <%=@user.email %>. Please check out in the Discovery menu section again once done.
    </td>
  </tr>
</table>

app/views/seed/distest.html.erb
<h4>Please read through the disclaimer before proceeding!</h4>

<div class="table"></div>
<div class="row">
  <div class=" col-md-9 col-lg-9">
    <b>Disclaimer: </b>
    <div class="row"> </div>
    <i>By click on the Discover button below, you <b><u> <%= link_to "confirm your user", user_path(@user) %> </b></u> email as <u><%= @user.email %></u>. And you have the exclusive permission to perform such discovery.
      You also agree to waive all your rights on the appliation programmer, and the site hosting provider.</i>
  </div>
</div>
<div class="col-md-9 col-lg-9"> </div>
    <div> </div>
    <p>
    <%= button_to("Discover", seed_discovery_path, class: "btn btn-primary") %>
    </br>
<div class="row"> </div>

app/views/seed/start.html.erb
<script type="text/javascript">
  $(document).ready(function() {
    var seed_editor = CodeMirror(document.getElementById("seedTextArea"), {
      mode: "null",
      lineNumbers: true,
      extraKeys: {
        "Ctrl-Space": "autocomplete"
      },
      value: ""
    });
    var seed_value =  $.ajax({
      url: "load_file",
      type: "GET",
      dataType: 'text',
      data: {
        "path": ""
      },
      success: function(response) {
        //console.log(response);
        //alert("Success: " + response['message'])
        seed_editor.getDoc().setValue(response);
      },
      error: function(response) {
        //console.log(response);
        alert("Error: " + response['message'])
      }
    });
    $('#save_seed_button').click(function() {
      $.ajax({
        url: "save_file",
        type: "POST",
        dataType: 'json',
        data: {
          "file_path": "",
          "file_content": seed_editor.getDoc().getValue()
        },
        success: function(response) {
          //console.log(response);
          if  (response['message']=="Access Denied.") {
            alert("Access Denied.")
          } else {
            alert("Success: " + response['message']);
            window.location = "/domains/import"
          }

        },
        error: function(response) {
          //console.log(response);
          alert("Error:" + response['message'])
        }
      });
    });
  });
</script>

<h4>  Discovery Seeds </h4>
<br />


<div class="row">

  <div class=" col-md-9 col-lg-9">
    <p>
    </br>
    <button type="button" class="pull-right btn btn-default" title="Discovery Seed Instructions"
      data-container="body" data-toggle="popover" data-placement="right"
      data-content="Discovery Seed Format: <br>
      <ul><li> One entry per line  </li>
          <li> Comment line start with special char # </li>
          <li> The entry can be an URL: https://x.x.x.x/ </li>
          <li> The entry can be full-qualified domain name: www.yoursite.com </li>
          <li> The entry can be an IP address: x.x.x.x </li>
          <li> The entry can be a network block in IPv4 CIDR format: x.x.x.x/24  </li>
      </ul>
          "><span class="glyphicon glyphicon-question-sign"></span>Seed Format</button>
    <div class="row"> </div>
    <div class ="CodeMirror" id="seedTextArea">
    </div>
    <div class="row"> </div>
    <button class="btn btn-primary" id="save_seed_button" type="submit">Save</button>

  </div>
</div>