config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}
  devise_scope :user do
    get 'users/list' => 'users#index'
    get 'users/report' => 'users#report'
    get 'users/:id' => 'users#show'
    delete '/users/logout' => 'devise/sessions#destroy'
  end
  get 'users/edit'
  post 'users/edit_save'
  resources :users
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  root 'home#page'
  get 'home/page'
  get 'home/support_contact'
  get 'home/about'

  get 'seed/start'
  post 'seed/start'
  get 'seed/load_file'
  post 'seed/save_file'
  post 'seed/discovery'
  get 'seed/distest'

  get 'domains/index'
  get 'domains/show'
  get 'domains/edit'
  post 'domains/edit_domain'
  post 'domains/save_domain'
  post 'domains/edit'
  post 'domains/update'
  delete 'domains/destroy'
  get 'domains/load_file'
  post 'domains/save_file'
  get 'domains/import'
  get 'domains/search'
  get 'domains/search_list'
  post 'domains/search_list'
  post 'domains/save_import'

  get 'cidrs/index'
  get 'cidrs/edit'
  get 'cidrs/import'
  post 'cidrs/save_import'
  post 'cidrs/edit'
  get 'cidrs/load_file'
  post 'cidrs/save_file'

  get 'hosts/index'
  post 'hosts/edit'
  get 'hosts/load_file'
  post 'hosts/save_file'

  get 'support/faq'
  get 'support/contact'

  get 'sites/index'
  get 'sites/show'
  post 'sites/edit'
  get 'sites/load_file'
  post 'sites/save_file'
  post 'sites/search'
  post 'sites/download'

  get 'logs/list'
  get 'logs/show'
  post 'logs/download'

  get 'yml_settings/index'
  get 'yml_settings/load_file'
  post 'yml_settings/save_file'

  get 'reports/index'
  get 'reports/new'
  get 'reports/download'
  get 'reports/download_all'
  resources :reports

  resources :uploads, only: [:new, :create, :destroy]
  get '/uploads/dt'
  get '/uploads/division_1'
  get '/uploads/division_2'
  get '/uploads/division_3'
  post "uploads/update"
  get "uploads/refresh"
  get "uploads/create"
  get "uploads/alert_uploads"

  get 'domain_map/show'
  post 'domain_map/show'

end

app/models/report.rb
#--
# www_wmap
#
# A  Ruby application for enterprise web application asset tracking
#
# Developed by Sam (Yang) Li, <yang.li@owasp.org>.
#
#++

class Report < ApplicationRecord
end

app/controllers/reports_controller.rb
#--
# www_wmap
#
# A  Ruby application for enterprise web application asset tracking
#
# Developed by Sam (Yang) Li, <yang.li@owasp.org>.
#
#++


class ReportsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_report, only: [:show, :edit, :update, :destroy]
  include ReportsHelper

  # Divisional domain portfolio report
  def division
    @reports = Report.where.not(division: [nil,""]).
                      where(category: "domain").
                      order(division: :ASC)
  end

  # Divisional Adware tag report
  def tag
    @reports = Report.where.not(division: [nil,""]).
                      where(category: "adware").
                      order(division: :ASC)
  end

  # GET /reports
  # GET /reports.json
  def index
    @reports = Report.all
  end

  # GET /reports/1
  # GET /reports/1.json
  def show
    report=Report.find(params[:id])
    if report.division.nil? or report.division.empty?
      case report.title
      when "All Domains"
        redirect_to domains_index_path
      when "All Networks"
        redirect_to cidrs_index_path
      when "All Hosts"
        redirect_to hosts_index_path
      when "All Websites"
        redirect_to sites_index_path
      when "All Adware Tags"
        redirect_to tags_index_path
      else
      end
    elsif report.category == "domain"
      redirect_to domains_show_path(division: report.division)
    elsif report.category == "adware"
      redirect_to tags_report_path(division: report.division)
    end
  end

  # GET /reports/new
  def new
    redirect_back :fallback_location => root_path, :alert => "Access denied." unless current_user.admin?
    @report = Report.new
  end

  # GET /reports/1/edit
  def edit
  end

  # provide pre-created divisional domain report in Excel workbook download
  def download
    if platinum_user_and_above?
      file_name = output(params[:division])
      file = Rails.root.join("downloads", file_name)
      if File.exist?(file)
        send_file(
          file,
          filename: file_name,
          type: "application/xlsx",
          disposition: "attachment"
        )
      else
        redirect_to reports_division_path, :flash => {:error => "File not found!"}
      end
    else
      redirect_back :fallback_location => root_path, :alert => "Access denied."
    end
  end

  # provide all domains report in Excel workbook download
  def download_all
    if platinum_user_and_above?
      @domains=Domain.where("name is not null")
      template = Rails.root.join("app","views","reports", "DomainPortfolio-template.xlsx")
      workbook = RubyXL::Parser.parse(template)
      worksheet = workbook.worksheets[0]
      worksheet.sheet_name = 'All'
      index = 0
      @domains.each do |domain|
        next if domain.name.nil?
        next if domain.name.empty?
        index += 1
        if domain.transferable
          my_row = [domain.name, "yes"]
        else
          my_row = [domain.name, "no"]
        end
        worksheet_write_row(worksheet,index, my_row)
      end
      file = "DomainPortfolio-All-" + Time.now.strftime('%m%d%Y') + ".xlsx"
      send_data workbook.stream.string, filename: file, disposition: 'attachment'
    else
      redirect_back :fallback_location => root_path, :alert => "Access denied."
    end
  end

  # provide all adware tag report in Excel workbook download
  def download_tags

  end

  # POST /reports
  # POST /reports.json
  def create
    if current_user.admin?
      @report = Report.new(report_params)
      respond_to do |format|
        if @report.save
          format.html { redirect_to @report, notice: 'Report was successfully created.' }
          format.json { render :show, status: :created, location: @report }
        else
          format.html { render :new }
          format.json { render json: @report.errors, status: :unprocessable_entity }
        end
      end
    else
      redirect_back :fallback_location => root_path, :alert => "Access denied."
    end
  end

  # PATCH/PUT /reports/1
  # PATCH/PUT /reports/1.json
  def update
    if  platinum_user_and_above?
      respond_to do |format|
        if @report.update(report_params)
          format.html { redirect_to @report, notice: 'Report was successfully updated.' }
          format.json { render :show, status: :ok, location: @report }
        else
          format.html { render :edit }
          format.json { render json: @report.errors, status: :unprocessable_entity }
        end
      end
    else
      respond_to do |format|
        format.html {
          redirect_back :fallback_location => root_path, :alert => "Access denied."
        }
        format.json {
          render json: { message: 'Access denied.' }
        }
      end

    end
  end

  # DELETE /reports/1
  # DELETE /reports/1.json
  def destroy
    if platinum_user_and_above?
      @report = Report.find(params[:id])
      file_name = output(@report.division)
      file = Rails.root.join("downloads", file_name)
      respond_to do |format|
        format.html {
          if File.exist?(file)
            File.unlink(file)
          end
          @report.destroy
          redirect_to reports_division_path, notice: 'Report '+ file_name + ' was successfully destroyed.'
        }
        format.json { head :no_content }
      end
    else
      respond_to do |format|
        format.html {
          redirect_back :fallback_location => root_path, :alert => "Access denied."
        }
        format.json {
          render json: { message: 'Access denied.' }
        }
      end
    end

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_report
      @report = Report.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def report_params
      params.require(:report).permit(:title, :description, :published)
    end
end

app/helpers/reports_helper.rb
#--
# www_wmap
#
# A  Ruby application for enterprise web application asset tracking
#
# Developed by Sam (Yang) Li, <yang.li@owasp.org>.
#
#++

module ReportsHelper
  # write an worksheet row
  def worksheet_write_row(worksheet, index, my_row)
    puts "Writing record into the spreadsheet: #{my_row}"
    (0...my_row.count).map do |col|
      worksheet.add_cell(index, 0, '') if worksheet[index].nil?
      worksheet.add_cell(index,col,'') if worksheet[index][col].nil?
      puts "Write to cell [#{index},#{col}]: #{my_row[col]}"
      worksheet[index][col].change_contents(my_row[col])
    end
  end

  # Determine download file name based on division
  def output(division)
    return "DomainPortfolio-" + division.strip + "-output.xlsx"
  end

end

app/views/reports/_form.html.erb
<%= form_with(model: report, local: true) do |form| %>
  <% if report.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(report.errors.count, "error") %> prohibited this report from being saved:</h2>

      <ul>
      <% report.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :published %>
    <%= form.check_box :published %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/reports/_mini_edit.html.erb
<div class="col-md-2 col-lg-2">
  <button class="btn btn-default dropdown-toggle " data-toggle="dropdown" align="left">
      Edit
      <span class="caret"></span>
  </button>
    <ul class="dropdown-menu">
        <li><%= link_to('Update', {controller: 'uploads', action: 'new'}) %></li>
        <li><%= link_to 'Delete', report_path(@report.id), method: :DELETE, data: {:confirm => "Are you sure delete report: #{@report.title}?"} %></li>
    </ul>
</div>

app/views/reports/division.html.erb
<h4>  Divisional Domain Portfolio Report </h4>
<br />

<table class="table table-bordered table-striped">
   <thead>
      <tr>
         <th>Name</th>
         <th>Division</th>
         <th>Download Link</th>
         <th>Action </th>
      </tr>
   </thead>

   <tbody>
      <% @reports.each do |report| %>
         <% @report=report %>
         <tr>
            <td><%= link_to report.title, domains_show_path(division: report.division), target: "_blank" %></td>
            <td><%= report.division %></td>
            <td><%= link_to image_tag("excel.png", class: "clickable-img", size: "35x35"), reports_download_path(:division => report.division), data: { turbolinks: false } %></td>
            <td><%= render 'mini_edit' unless report.title.nil? %></td>
         </tr>
      <% end %>
   </tbody>
</table>

app/views/reports/edit.html.erb
<h1>Editing Report</h1>

<%= render 'form', report: @report %>

<%= link_to 'Show', @report %> |
<%= link_to 'Back', reports_path %>

app/views/reports/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Reports</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Published</th>
      <th colspan="3">   &nbsp&nbsp&nbsp Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @reports.each do |report| %>
      <tr>
        <td><%= report.title %></td>
        <td><%= report.description %></td>
        <td><%= report.published %></td>
        <td><%= link_to 'Show', report %></td>
        <td><%= link_to 'Edit', edit_report_path(report) %></td>
        <td><%= link_to 'Destroy', report, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Report', new_report_path %>

app/views/reports/new.html.erb
<h1>New Report</h1>

<%= render 'form', report: @report %>

<%= link_to 'Back', reports_path %>

app/views/reports/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @report.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @report.description %>
</p>

<p>
  <strong>Published:</strong>
  <%= @report.published %>
</p>

<%= link_to 'Edit', edit_report_path(@report) %> |
<%= link_to 'Back', reports_path %>

app/views/reports/tag.html.erb
<h4>  Divisional Adware Portfolio Report </h4>
<br />

<table class="table table-bordered table-striped">
   <thead>
      <tr>
         <th>Name</th>
         <th>Division</th>
         <th>Download Link</th>
      </tr>
   </thead>

   <tbody>
      <% @reports.each do |report| %>
         <% @report=report %>
         <tr>
            <td><%= link_to report.title, tags_report_path(division: report.division), target: "_blank" %></td>
            <td><%= report.division %></td>
            <td><%= link_to image_tag("excel.png", class: "clickable-img", size: "35x35"), tags_download_path(:division => report.division), data: { turbolinks: false } %></td>
         </tr>
      <% end %>
   </tbody>
</table>